# Assignment # 6

## Names:
- Trishla Nair
- Ruixin Han

## Import:

In [44]:
import pandas as pd
import math
import numpy as np
import ipywidgets 
import bqplot
import bqplot.pyplot as plt
from datetime import datetime as dt

In [45]:
ipywidgets.IntSlider(
    value=7,
    min=0,
    max=10,
    step=1,
    description='Test:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

IntSlider(value=7, continuous_update=False, description='Test:', max=10)

In [46]:
df = pd.read_csv('https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/licenses_fall2022.csv')
df

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Specialty/Qualifier,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason
0,1189509,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129446286,NOT RENEWED,N,NaN,EILEEN,NaN,SANTACRUZ,...,None,None,None,N,03/18/2022,None,None,None,None,None
1,801037,DETECTIVE BOARD,FIREARM CONTROL CARD,229030294.0,NOT RENEWED,N,NaN,DAGMAR,J,NORDLUND,...,None,None,None,N,08/16/2006,None,None,None,None,None
2,365129,COSMO,LICENSED COSMETOLOGIST,11053076.0,NOT RENEWED,N,NaN,RADOJE,NaN,ZELENOVIC,...,None,None,None,N,05/26/2006,None,None,None,None,None
3,595427,COSMO,LICENSED COSMETOLOGIST,11295645.0,ACTIVE,N,NaN,BECKY SUE,L,BURROUGHS,...,None,None,None,N,11/12/2021,None,None,None,None,None
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,None,None,None,N,05/30/2006,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,888281,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129002843.0,NOT RENEWED,N,NaN,JENNIFER,NaN,DARROW,...,None,None,None,N,08/03/2006,None,None,None,None,None
9996,766623,DETECTIVE BOARD,FIREARM CONTROL CARD,229014180,TERMINATED CARD RETURNED,N,NaN,BRYAN,NaN,WILLIAMS,...,None,None,None,N,08/07/2006,None,None,None,None,None
9997,399398,COSMO,LICENSED COSMETOLOGIST,11120249,NOT RENEWED,N,NaN,EUGENE,NaN,HENDERSON JR,...,None,None,None,N,05/26/2006,None,None,None,None,None
9998,486713,COSMO,LICENSED COSMETOLOGIST,11193270,ACTIVE,N,NaN,MAHLON DOUGLAS,NaN,CLIFT,...,None,None,None,N,12/17/2021,None,None,None,None,None
9999,744770,DENTAL,REGISTERED DENTAL HYGIENIST,020012709,ACTIVE,N,NaN,KAREEM,L,HARRIS,...,None,None,None,N,10/25/2021,None,None,None,None,None

In [47]:
df = df.fillna(0)
df = pd.read_csv('https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/licenses_fall2022.csv', na_values = ['None'])
df

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,Specialty/Qualifier,Controlled Substance Schedule,Delegated Controlled Substance Schedule,Ever Disciplined,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason
0,1189509,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129446286,NOT RENEWED,N,NaN,EILEEN,NaN,SANTACRUZ,...,NaN,NaN,NaN,N,03/18/2022,NaN,NaN,NaN,NaN,NaN
1,801037,DETECTIVE BOARD,FIREARM CONTROL CARD,229030294.0,NOT RENEWED,N,NaN,DAGMAR,J,NORDLUND,...,NaN,NaN,NaN,N,08/16/2006,NaN,NaN,NaN,NaN,NaN
2,365129,COSMO,LICENSED COSMETOLOGIST,11053076.0,NOT RENEWED,N,NaN,RADOJE,NaN,ZELENOVIC,...,NaN,NaN,NaN,N,05/26/2006,NaN,NaN,NaN,NaN,NaN
3,595427,COSMO,LICENSED COSMETOLOGIST,11295645.0,ACTIVE,N,NaN,BECKY SUE,L,BURROUGHS,...,NaN,NaN,NaN,N,11/12/2021,NaN,NaN,NaN,NaN,NaN
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,NaN,NaN,NaN,N,05/30/2006,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,888281,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129002843.0,NOT RENEWED,N,NaN,JENNIFER,NaN,DARROW,...,NaN,NaN,NaN,N,08/03/2006,NaN,NaN,NaN,NaN,NaN
9996,766623,DETECTIVE BOARD,FIREARM CONTROL CARD,229014180,TERMINATED CARD RETURNED,N,NaN,BRYAN,NaN,WILLIAMS,...,NaN,NaN,NaN,N,08/07/2006,NaN,NaN,NaN,NaN,NaN
9997,399398,COSMO,LICENSED COSMETOLOGIST,11120249,NOT RENEWED,N,NaN,EUGENE,NaN,HENDERSON JR,...,NaN,NaN,NaN,N,05/26/2006,NaN,NaN,NaN,NaN,NaN
9998,486713,COSMO,LICENSED COSMETOLOGIST,11193270,ACTIVE,N,NaN,MAHLON DOUGLAS,NaN,CLIFT,...,NaN,NaN,NaN,N,12/17/2021,NaN,NaN,NaN,NaN,NaN
9999,744770,DENTAL,REGISTERED DENTAL HYGIENIST,020012709,ACTIVE,N,NaN,KAREEM,L,HARRIS,...,NaN,NaN,NaN,N,10/25/2021,NaN,NaN,NaN,NaN,NaN

In [48]:
df['Original Issue Date'] = pd.to_datetime(df['Original Issue Date'],errors='coerce',format='%m/%d/%Y')
df['Original Issue Year'] = df['Original Issue Date'].dt.year

df['Expiration Date'] = pd.to_datetime(df['Expiration Date'],errors='coerce',format='%m/%d/%Y')
df['Expiration Year'] = df['Expiration Date'].dt.year

In [49]:
df['License Type'].value_counts()

DETECTIVE BOARD           4867
COSMO                     3781
DENTAL                     739
FUNERAL AND EMBALMER        98
DIETETIC AND NUTRITION      73
DESIGN FIRM                 71
MASSAGE LICENSING BD        52
HOME INSPECTOR              46
COMM ASSOC MGR              37
CLIN PSYCHOLOGIST           24
INTERIOR DESIGN             22
COLLECTION AGENCY           21
LIMITED LIABILITY CO        21
ARCHITECT                   20
LAND SURVEYOR BOARD         17
HME AND SERVICES PROV       16
ATHLETICS                   15
MAR AND FAM THERAPIST       14
ATHLETIC TRAINER            14
ENVIRON. HLTH PRACT         13
IDPR                         9
GEOLOGY                      7
LANDSCAPE ARCHITECT          7
MEDICAL BOARD                6
APPRAISAL                    5
DETECT. DECEPTION            2
AUCTIONEER                   2
CEMETERY OVERSIGHT           1
Name: License Type, dtype: int64

## Left Side:

In [50]:
df['Difference_Days'] = df['Expiration Date'] - df['Original Issue Date']
df['Difference_Days'] = df['Difference_Days'].dt.days
df['Difference_Days'].mean()
print(df['Difference_Days'])

0         605.0
1        3249.0
2       14093.0
3        4330.0
4        2668.0
         ...
9995     3588.0
9996      385.0
9997        NaN
9998    14606.0
9999     5828.0
Name: Difference_Days, Length: 10000, dtype: float64

In [51]:
ndf = df[['County', 'License Type', 'Original Issue Year', 'Expiration Year', 'Difference_Days']]
ndf

,County,License Type,Original Issue Year,Expiration Year,Difference_Days
0,COOK,DETECTIVE BOARD,2020.0,2021.0,605.0
1,KANE,DETECTIVE BOARD,1995.0,2003.0,3249.0
2,COOK,COSMO,1945.0,1983.0,14093.0
3,DUPAGE,COSMO,2011.0,2023.0,4330.0
4,COOK,COSMO,1995.0,2002.0,2668.0
...,...,...,...,...,...
9995,WILL,DETECTIVE BOARD,1987.0,1997.0,3588.0
9996,COOK,DETECTIVE BOARD,1989.0,1990.0,385.0
9997,COOK,COSMO,1966.0,NaN,NaN
9998,COOK,COSMO,1983.0,2023.0,14606.0
9999,MCHENRY,DENTAL,2008.0,2024.0,5828.0

In [52]:
table1 = pd.pivot_table(ndf, values= 'Difference_Days', index= 'County' , columns= 'License Type', aggfunc=np.mean, fill_value = 0)
table1

License Type,APPRAISAL,ARCHITECT,ATHLETIC TRAINER,ATHLETICS,AUCTIONEER,CEMETERY OVERSIGHT,CLIN PSYCHOLOGIST,COLLECTION AGENCY,COMM ASSOC MGR,COSMO,...,HME AND SERVICES PROV,HOME INSPECTOR,IDPR,INTERIOR DESIGN,LAND SURVEYOR BOARD,LANDSCAPE ARCHITECT,LIMITED LIABILITY CO,MAR AND FAM THERAPIST,MASSAGE LICENSING BD,MEDICAL BOARD
County,,,,,,,,,,,,,,,,,,,,,
ADAMS,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,4026.363636,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,1392.0,0
ALABAMA,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,454.500000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
ALEXANDER,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,1066.000000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
ARIZONA,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,643.692308,...,0.0,0.0,0.0,2962.0,0,0,0.000000,0.0,0.0,0
ARKANSAS,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,2858.500000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WILLIAMSON,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,3386.882353,...,7892.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
WINNEBAGO,0.0,0.0,0.0,0.0,0,0,0.0,1051.0,0.0,4585.777778,...,0.0,4774.0,865.0,0.0,0,0,2228.666667,709.0,0.0,0
WISCONSIN,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,2731.166667,...,882.0,3375.0,0.0,9882.0,5083,2540,0.000000,0.0,0.0,0
WOODFORD,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,5271.384615,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
WYOMING,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0

In [53]:
table1.shape

(140, 27)

In [54]:
# HEATMAP
# 2. scales
col_sc = bqplot.ColorScale(scheme='Blues')# <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, label='Mean', orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc, label = 'License Type', tick_rotate=45, tick_style = {'font-size': '6px', 'text-anchor': 'start'}, 
                   label_offset = '55px')
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label = 'County', tick_style = {'font-size': '6px'}, label_offset = '50px')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=table1, 
                              row=table1.index.values.astype('str'),
                              column=table1.columns.values.astype('str'),
                              scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions



def get_data_value(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i,j = change['owner'].selected[0]
        county_name=table.index.values.astype('str')[i]
        license_type=table.columns.values.astype('str')[j]
        region_mask = ( (license['County']==county_name) &\
              (license['License Type']==license_type))
        data=license.loc[region_mask]
        data_y=data.groupby('Original Issue Year')['days between Original Issue Date and Expiration Date'].median()
        bar.x = data['Original Issue Year']
        bar.y = data_y

        
        
heat_map.observe(get_data_value, 'selected')

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(label='Mean', orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), …

## Right:

In [55]:
i=3
j=10
table1.index.values.astype('str')[i]
county_name=table1.index.values.astype('str')[i]
ndf['County']==county_name
ndf.loc[ndf['County']==county_name]

,County,License Type,Original Issue Year,Expiration Year,Difference_Days
159,ARIZONA,COSMO,1998.0,1981.0,-5936.0
595,ARIZONA,DENTAL,1971.0,1990.0,7024.0
1023,ARIZONA,COSMO,1998.0,1989.0,-3015.0
1361,ARIZONA,DENTAL,1980.0,2022.0,15175.0
1554,ARIZONA,COSMO,1998.0,1987.0,-3746.0
1659,ARIZONA,COSMO,1973.0,1987.0,5313.0
1746,ARIZONA,INTERIOR DESIGN,1997.0,2005.0,2962.0
1783,ARIZONA,COSMO,1949.0,1983.0,12372.0
1844,ARIZONA,DESIGN FIRM,2018.0,2023.0,1641.0
2024,ARIZONA,COSMO,1998.0,NaN,NaN
3036,ARIZONA,COSMO,1998.0,1983.0,-5207.0
3038,ARIZONA,COSMO,1998.0,NaN,NaN
4752,ARIZONA,DENTAL,1975.0,2015.0,14841.0
4878,ARIZONA,DETECTIVE BOARD,2008.0,2009.0,291.0
5230,ARIZONA,COSMO,1993.0,1999.0,2397.0
5902,ARIZONA,COSMO,1983.0,2003.0,7498.0
6228,ARIZONA,COSMO,1998.0,1999.0,330.0
6512,ARIZONA,FUNERAL AND EMBALMER,2013.0,2023.0,3773.0
7776,ARIZONA,COSMO,1998.0,1986.0,-4111.0
8038,ARIZONA,COSMO,1998.0,NaN,NaN
8228,ARIZONA,DENTAL,1929.0,1994.0,23790.0
8632,ARIZONA,COSMO,1998.0,1987.0,-3746.0
8925,ARIZONA,DENTAL,1970.0,2004.0,12504.0
9024,ARIZONA,DETECTIVE BOARD,1994.0,1997.0,897.0
9179,ARIZONA,COSMO,1990.0,1993.0,1345.0
9673,ARIZONA,COSMO,2004.0,2017.0,4874.0

In [56]:
table1.columns.values.astype('str')[j]
license_type=table1.columns.values.astype('str')[j]
ndf['License Type']==license_type
ndf.loc[ndf['License Type']==license_type]
            
region_mask = ( (ndf['County']==county_name) &\
              (ndf['License Type']==license_type))
data=ndf.loc[region_mask]
data_y=data.groupby(['Original Issue Year'])['Difference_Days'].median()

In [57]:
# BAR chart
x_scl = bqplot.OrdinalScale()
y_scl = bqplot.LinearScale()

# (2) Axis
ax_xcl = bqplot.Axis(label='Date', scale=x_scl)
ax_ycl = bqplot.Axis(label='Median Day difference', scale=y_scl, 
                    orientation='vertical', side='left')

bar = bqplot.Bars(x=data['Original Issue Year'], y=data_y, scales={"x": x_scl, "y": y_scl})
ax_x = bqplot.Axis(scale=x_scl)
ax_y = bqplot.Axis(scale=y_scl, orientation="vertical")

bqplot.Figure(marks=[bar], axes=[ax_xcl, ax_ycl])

Figure(axes=[Axis(label='Date', scale=OrdinalScale()), Axis(label='Median Day difference', orientation='vertic…

## Linking

In [58]:
fig = bqplot.Figure(marks = [heat_map], axes = [col_ax, y_ax, x_ax])
fig_bar = bqplot.Figure(marks = [bar], axes = [ax_xcl, ax_ycl])

In [59]:
bqplot.__version__

'0.12.30'

In [60]:
#!jupyter nbextension enable --py bqplot

In [61]:
size = 100
scale = 100.0
np.random.seed(0)
x_data = np.arange(size)
y_data = np.cumsum(np.random.randn(size) * scale)

In [62]:
from IPython.display import display

fig = plt.figure(title="First Example")
plt.plot(y_data)
display(fig)

Figure(axes=[Axis(scale=LinearScale()), Axis(orientation='vertical', scale=LinearScale())], fig_margin={'top':…

In [63]:
from bqplot import pyplot as plt
import pandas as pd

apple_df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
print(apple_df)
fig = plt.figure(title="Apple Mar-2020 CandleStick Chart")

fig.layout.width="800px"


ohlc = plt.ohlc(x=apple_df.index, y=apple_df[["AAPL.Open","AAPL.High","AAPL.Low","AAPL.Close"]],
                marker="candle", stroke="blue")

ohlc.colors=["lime", "tomato"]
plt.xlabel("Date")

plt.show()

           Date   AAPL.Open   AAPL.High    AAPL.Low  AAPL.Close  AAPL.Volume  \
0    2015-02-17  127.489998  128.880005  126.919998  127.830002     63152400
1    2015-02-18  127.629997  128.779999  127.449997  128.720001     44891700
2    2015-02-19  128.479996  129.029999  128.330002  128.449997     37362400
3    2015-02-20  128.619995  129.500000  128.050003  129.500000     48948400
4    2015-02-23  130.020004  133.000000  129.660004  133.000000     70974100
..          ...         ...         ...         ...         ...          ...
501  2017-02-10  132.460007  132.940002  132.050003  132.119995     20065500
502  2017-02-13  133.080002  133.820007  132.750000  133.289993     23035400
503  2017-02-14  133.470001  135.089996  133.250000  135.020004     32815500
504  2017-02-15  135.520004  136.270004  134.619995  135.509995     35501600
505  2017-02-16  135.669998  135.899994  134.839996  135.350006     22118000

     AAPL.Adjusted          dn        mavg          up   direction
0       122.905254  106.741052  117.927667  129.114281  Increasing
1       123.760965  107.842423  118.940333  130.038244  Increasing
2       123.501363  108.894245  119.889167  130.884089  Decreasing
3       124.510914  109.785449  120.763500  131.741551  Increasing
4       127.876074  110.372516  121.720167  133.067817  Increasing
..             ...         ...         ...         ...         ...
501     132.119995  114.494004  124.498666  134.503328  Decreasing
502     133.289993  114.820798  125.205166  135.589534  Increasing
503     135.020004  115.175718  125.953499  136.731280  Increasing
504     135.509995  115.545035  126.723499  137.901963  Decreasing
505     135.350006  116.203299  127.504333  138.805366  Decreasing

[506 rows x 11 columns]

VBox(children=(Figure(axes=[Axis(label='Date', scale=LinearScale()), Axis(orientation='vertical', scale=Linear…

In [64]:
# mess with figure layout:
fig.layout.min_width = '550px' 
fig.layout.min_width = '550px'

# side by side figures
figures = ipywidgets.HBox([fig, fig_bar])


# combined
myDashboard = ipywidgets.VBox([figures])
myDashboard

VBox(children=(HBox(children=(Figure(axes=[Axis(label='Date', scale=LinearScale()), Axis(orientation='vertical…

##  Write-up

    For this aaignment, we (Ruixin and I) created 2 vizualizations an had to link them together with the provided sata. In the data, there are some NAN  values. We left the NAN values as is because they represent data that was difficult to get from their respective observation. When constructing the vizualizations, we left the cosmetics as a minimum mainly to keep it simple. However, Blue was chosen because blue tends to be one of the few colors people don't have trouble seeing. In regards to scaling, depending on wether the data for the axis is numerical or categorical, one oof 2 scales were chosen that was available to bqplot: ordinal scales or linear scales. Ordinal scales were used for categorical data and linear scales were used for numerical data. 
    The first vizual that was created was the heat map. The heat map looks at how long it took for each license lasted in each county, with the difference indicated by the color saturation. The other vizual created was a bar graph. The bar graph looks into the median number of days between expiration and original issue date in respect to years. To accomplish creating the visuals, we had to reffer to some online resources and documentations regarding the way bqplot functions as well as the additional resources provided.
    The most complicated sapect of the assignment was linking the data as it. In my perspective, the reason why it was difficult was because there was a similar example but it looked very complicated. But really it's less complicated than it actually is. However, for my end of the data, once the vizualizations were linked and the dashboard was created, an error is shown for  an unsupported dtype object. I believe it may be an issue that I am running into on only my computer however because the wxample that is similar to this situation also produces a similar data. Nonetheless, I am sure this was the correct way to link the data.However, in other ways about the interactiveness of the dashboard, users cannot do much with the dashboard such as change the colors shown, or the columns.