### Group 2

Group members: Trishla Nair, Ruixin Han

In [1]:
import pandas as pd
import bqplot
import numpy as np
import traitlets
import ipywidgets
import matplotlib.pyplot as plt

In [2]:
license = pd.read_csv("https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_bcubcg_fall2022/main/data/licenses_fall2022.csv")

In [3]:
license['Original Issue Date'] = pd.to_datetime(license["Original Issue Date"],
                                           format='%m/%d/%Y', 
                                           errors='coerce')
license['Expiration Date'] = pd.to_datetime(license["Expiration Date"],
                                           format='%m/%d/%Y', 
                                           errors='coerce')

In [4]:
license['days between Original Issue Date and Expiration Date'] = (license['Expiration Date'] - license['Original Issue Date']).dt.days
license['days between Original Issue Date and Expiration Date']

0         605.0
1        3249.0
2       14093.0
3        4330.0
4        2668.0
         ...
9995     3588.0
9996      385.0
9997        NaN
9998    14606.0
9999     5828.0
Name: days between Original Issue Date and Expiration Date, Length: 10000, dtype: float64

In [5]:
# Barplot/histogram
x_scl = bqplot.LinearScale() # note we are back to linears
y_scl = bqplot.LinearScale()
ax_xcl = bqplot.Axis(label='Year', scale=x_scl)
ax_ycl = bqplot.Axis(label='Median number of days between Original Issue Date and Expiration Date', scale=y_scl, 
                    orientation='vertical', side='right')

# hist = bqplot.Hist(sample = data3d[0,0,:],
#                    normalized = False, # normalized=False means we get counts in each bin
#                    scales = {'sample': x_sch, 'count': y_sch}, # sample is data values, count is frequency
#                    bins = 5) # number of bins

In [6]:
license['Original Issue Year'] = license['Original Issue Date'].dt.year
license['Expiration Year'] = license['Expiration Date'].dt.year
license['Year'] = license.groupby(['Original Issue Year'])['Expiration Year'].transform('count')
license['Year']
license

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason,days between Original Issue Date and Expiration Date,Original Issue Year,Expiration Year,Year
0,1189509,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129446286,NOT RENEWED,N,NaN,EILEEN,NaN,SANTACRUZ,...,03/18/2022,None,None,None,None,None,605.0,2020.0,2021.0,187.0
1,801037,DETECTIVE BOARD,FIREARM CONTROL CARD,229030294.0,NOT RENEWED,N,NaN,DAGMAR,J,NORDLUND,...,08/16/2006,None,None,None,None,None,3249.0,1995.0,2003.0,290.0
2,365129,COSMO,LICENSED COSMETOLOGIST,11053076.0,NOT RENEWED,N,NaN,RADOJE,NaN,ZELENOVIC,...,05/26/2006,None,None,None,None,None,14093.0,1945.0,1983.0,4.0
3,595427,COSMO,LICENSED COSMETOLOGIST,11295645.0,ACTIVE,N,NaN,BECKY SUE,L,BURROUGHS,...,11/12/2021,None,None,None,None,None,4330.0,2011.0,2023.0,213.0
4,653668,COSMO,LICENSED NAIL TECHNICIAN,169006247,NOT RENEWED,N,NaN,BILL G,L,LETNER,...,05/30/2006,None,None,None,None,None,2668.0,1995.0,2002.0,290.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,888281,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129002843.0,NOT RENEWED,N,NaN,JENNIFER,NaN,DARROW,...,08/03/2006,None,None,None,None,None,3588.0,1987.0,1997.0,200.0
9996,766623,DETECTIVE BOARD,FIREARM CONTROL CARD,229014180,TERMINATED CARD RETURNED,N,NaN,BRYAN,NaN,WILLIAMS,...,08/07/2006,None,None,None,None,None,385.0,1989.0,1990.0,194.0
9997,399398,COSMO,LICENSED COSMETOLOGIST,11120249,NOT RENEWED,N,NaN,EUGENE,NaN,HENDERSON JR,...,05/26/2006,None,None,None,None,None,NaN,1966.0,NaN,15.0
9998,486713,COSMO,LICENSED COSMETOLOGIST,11193270,ACTIVE,N,NaN,MAHLON DOUGLAS,NaN,CLIFT,...,12/17/2021,None,None,None,None,None,14606.0,1983.0,2023.0,98.0
9999,744770,DENTAL,REGISTERED DENTAL HYGIENIST,020012709,ACTIVE,N,NaN,KAREEM,L,HARRIS,...,10/25/2021,None,None,None,None,None,5828.0,2008.0,2024.0,205.0

In [7]:
license['Original Issue Year']

0       2020.0
1       1995.0
2       1945.0
3       2011.0
4       1995.0
         ...
9995    1987.0
9996    1989.0
9997    1966.0
9998    1983.0
9999    2008.0
Name: Original Issue Year, Length: 10000, dtype: float64

In [8]:
license_Year = pd.pivot_table(license, values='days between Original Issue Date and Expiration Date', index=['Original Issue Year'], columns=['Expiration Year'],
                      aggfunc=np.median, fill_value=0)
license_Year

Expiration Year,1967.0,1977.0,1979.0,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,...,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0,2099.0
Original Issue Year,,,,,,,,,,,,,,,,,,,,,
1926.0,0,0.0,0,0.0,0.0,0.0,0.0,21181,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1928.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1929.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1930.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1933.0,0,0.0,0,0.0,0.0,0.0,18502.5,18666,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,148.0,420.5,974.0,1170.0,1431.0,1870.0,2174.0,2310.0,0.0
2019.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,187.5,619.0,833.0,1096.0,1513.0,1858.0,1871.0,0.0
2020.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,102.0,504.0,785.5,1095.0,1423.0,0.0,0.0
2021.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,234.5,498.0,778.5,1064.5,1119.5,0.0
2022.0,0,0.0,0,0.0,0.0,0.0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,254.0,557.0,809.0,1096.0,0.0

In [9]:
license_Year=license.groupby('Original Issue Year')['days between Original Issue Date and Expiration Date'].median().reset_index()
license_Year

    Original Issue Year  days between Original Issue Date and Expiration Date
0                1912.0                                                NaN
1                1918.0                                                NaN
2                1919.0                                                NaN
3                1923.0                                                NaN
4                1926.0                                            22228.5
..                  ...                                                ...
95               2018.0                                             1287.0
96               2019.0                                             1096.0
97               2020.0                                             1013.0
98               2021.0                                              957.5
99               2022.0                                              770.0

[100 rows x 2 columns]

In [10]:
import bqplot.pyplot as plt
from bqplot import Tooltip
fig_bar = plt.figure(title="Median Days between Original Issue Date and Expiration Date")
bar_chart = plt.bar(x = license_Year['Original Issue Year'], y = license_Year['days between Original Issue Date and Expiration Date'])
bar_chart.colors = ["green"]
bar_chart.tooltip = Tooltip(fields=["x", "y"], labels=["Original Issue Year", "Median days"])
plt.xlabel("Original Issue Year")
plt.ylabel("Median days")

plt.show()

VBox(children=(Figure(axes=[Axis(label='Original Issue Year', scale=LinearScale()), Axis(label='Median days', …

In [11]:
table = pd.pivot_table(license, values= 'days between Original Issue Date and Expiration Date', index= ['County'] , columns= ['License Type'] ,
                      aggfunc=np.mean, fill_value = 0)
table

License Type,APPRAISAL,ARCHITECT,ATHLETIC TRAINER,ATHLETICS,AUCTIONEER,CEMETERY OVERSIGHT,CLIN PSYCHOLOGIST,COLLECTION AGENCY,COMM ASSOC MGR,COSMO,...,HME AND SERVICES PROV,HOME INSPECTOR,IDPR,INTERIOR DESIGN,LAND SURVEYOR BOARD,LANDSCAPE ARCHITECT,LIMITED LIABILITY CO,MAR AND FAM THERAPIST,MASSAGE LICENSING BD,MEDICAL BOARD
County,,,,,,,,,,,,,,,,,,,,,
ADAMS,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,4026.363636,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,1392.0,0
ALABAMA,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,454.500000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
ALEXANDER,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,1066.000000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
ARIZONA,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,643.692308,...,0.0,0.0,0.0,2962.0,0,0,0.000000,0.0,0.0,0
ARKANSAS,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,2858.500000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WILLIAMSON,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,3386.882353,...,7892.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
WINNEBAGO,0.0,0.0,0.0,0.0,0,0,0.0,1051.0,0.0,4585.777778,...,0.0,4774.0,865.0,0.0,0,0,2228.666667,709.0,0.0,0
WISCONSIN,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,2731.166667,...,882.0,3375.0,0.0,9882.0,5083,2540,0.000000,0.0,0.0,0
WOODFORD,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,5271.384615,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0
WYOMING,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0,0,0.000000,0.0,0.0,0

In [12]:
# HEATMAP
# 2. scales
col_sc = bqplot.ColorScale(scheme='Blues')# <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, label='Mean', orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc,label='License Type',tick_rotate=90)
y_ax = bqplot.Axis(scale=y_sc, label='County', orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=table, 
                              row=table.index.values.astype('str'),
                              column=table.columns.values.astype('str'),
                              scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions
def get_data_value(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i,j = change['owner'].selected[0]
        print(i,j)
heat_map.observe(get_data_value, 'selected')


fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(label='Mean', orientation='vertical', scale=ColorScale(scheme='Blues'), side='right'), …

In [13]:
table.index.values.astype('str')

array(['ADAMS', 'ALABAMA', 'ALEXANDER', 'ARIZONA', 'ARKANSAS', 'BOND',
       'BOONE', 'BROWN', 'BUREAU', 'CALIFORNIA', 'CARROLL', 'CASS',
       'CHAMPAIGN', 'CHRISTIAN', 'CLARK', 'CLAY', 'CLINTON', 'COLES',
       'COLORADO', 'COOK', 'CRAWFORD', 'CUMBERLAND', 'DE WITT', 'DEKALB',
       'DOUGLAS', 'DUPAGE', 'EDGAR', 'EDWARDS', 'EFFINGHAM', 'FAYETTE',
       'FLORIDA', 'FORD', 'FRANKLIN', 'FULTON', 'GALLATIN', 'GEORGIA',
       'GREENE', 'GRUNDY', 'HAMILTON', 'HANCOCK', 'HARDIN', 'HAWAII',
       'HENDERSON', 'HENRY', 'IDAHO', 'INDIANA', 'IOWA', 'IROQUOIS',
       'JACKSON', 'JASPER', 'JEFFERSON', 'JERSEY', 'JO DAVIESS',
       'JOHNSON', 'KANE', 'KANKAKEE', 'KANSAS', 'KENDALL', 'KENTUCKY',
       'KNOX', 'LA SALLE', 'LAKE', 'LAWRENCE', 'LEE', 'LIVINGSTON',
       'LOGAN', 'LOUISIANA', 'MACON', 'MACOUPIN', 'MADISON', 'MARION',
       'MARSHALL', 'MARYLAND', 'MASON', 'MASSAC', 'MASSACHUSETTS',
       'MCDONOUGH', 'MCHENRY', 'MCLEAN', 'MENARD', 'MERCER',
       'MICHIGAN           ', 'MINNESOTA          ', 'MISSISSIPPI',
       'MISSOURI           ', 'MONROE', 'MONTANA            ',
       'MONTGOMERY', 'MORGAN', 'MOULTRIE', 'NEVADA             ',
       'NEW HAMPSHIRE      ', 'NEW JERSEY         ',
       'NEW MEXICO         ', 'NEW YORK           ',
       'NORTH CAROLINA     ', 'NORTH DAKOTA       ', 'OGLE',
       'OHIO               ', 'OKLAHOMA           ',
       'OREGON             ', 'PENNSYLVANIA       ', 'PEORIA', 'PERRY',
       'PIATT', 'PIKE', 'POPE', 'PULASKI', 'PUTNAM', 'RANDOLPH',
       'RICHLAND', 'ROCK ISLAND', 'SAINT CLAIR', 'SALINE', 'SANGAMON',
       'SCHUYLER', 'SCOTT', 'SHELBY', 'SOUTH CAROLINA     ', 'STARK',
       'STEPHENSON', 'TAZEWELL', 'TENNESSEE          ',
       'TEXAS              ', 'UNION', 'UTAH               ', 'VERMILION',
       'VIRGINIA           ', 'WABASH', 'WARREN', 'WASHINGTON', 'WAYNE',
       'WHITE', 'WHITESIDE', 'WILL', 'WILLIAMSON', 'WINNEBAGO',
       'WISCONSIN          ', 'WOODFORD', 'WYOMING            '],
      dtype='<U19')

In [14]:
table.columns.values.astype('str')

array(['APPRAISAL', 'ARCHITECT', 'ATHLETIC TRAINER', 'ATHLETICS',
       'AUCTIONEER', 'CEMETERY OVERSIGHT', 'CLIN PSYCHOLOGIST',
       'COLLECTION AGENCY', 'COMM ASSOC MGR', 'COSMO', 'DENTAL',
       'DESIGN FIRM', 'DETECTIVE BOARD', 'DIETETIC AND NUTRITION',
       'ENVIRON. HLTH PRACT', 'FUNERAL AND EMBALMER', 'GEOLOGY',
       'HME AND SERVICES PROV', 'HOME INSPECTOR', 'IDPR',
       'INTERIOR DESIGN', 'LAND SURVEYOR BOARD', 'LANDSCAPE ARCHITECT',
       'LIMITED LIABILITY CO', 'MAR AND FAM THERAPIST',
       'MASSAGE LICENSING BD', 'MEDICAL BOARD'], dtype='<U22')

In [15]:
i=3
j=10
table.index.values.astype('str')[i]
county_name=table.index.values.astype('str')[i]
license['County']==county_name
license.loc[license['County']==county_name]

,_id,License Type,Description,License Number,License Status,Business,Title,First Name,Middle,Last Name,...,LastModifiedDate,Case Number,Action,Discipline Start Date,Discipline End Date,Discipline Reason,days between Original Issue Date and Expiration Date,Original Issue Year,Expiration Year,Year
159,612456,COSMO,LICENSED COSMETOLOGIST TEACHER,12002401.0,NOT RENEWED,N,NaN,JONI K,NaN,HOOK,...,05/26/2006,None,None,None,None,None,-5936.0,1998.0,1981.0,857.0
595,734287,DENTAL,REGISTERED DENTAL HYGIENIST,020001463,INACTIVE,N,NaN,JOHN,NaN,SIMONE,...,10/12/2005,None,None,None,None,None,7024.0,1971.0,1990.0,17.0
1023,384152,COSMO,LICENSED COSMETOLOGIST,11098370,INACTIVE,N,NaN,ANN-ROSE N,NaN,TUMAR,...,05/26/2006,None,None,None,None,None,-3015.0,1998.0,1989.0,857.0
1361,697282,DENTAL,REGISTERED DENTAL HYGIENIST,020004206,NOT RENEWED,N,NaN,ANDREW J,NaN,MARINO,...,05/09/2022,None,None,None,None,None,15175.0,1980.0,2022.0,87.0
1554,355036,COSMO,LICENSED COSMETOLOGIST,11044172.0,INACTIVE,N,NaN,RICHARD,NaN,CAPIZZANO,...,05/26/2006,None,None,None,None,None,-3746.0,1998.0,1987.0,857.0
1659,441052,COSMO,LICENSED COSMETOLOGIST,11151504,NOT RENEWED,N,NaN,MARY,NaN,LONGHINI,...,05/26/2006,None,None,None,None,None,5313.0,1973.0,1987.0,56.0
1746,1245891,INTERIOR DESIGN,REGISTERED RESIDENTIAL INTERIOR DESIGNER,185000278,NOT RENEWED,N,NaN,KIMBERLY,NaN,THOMEY,...,10/17/2005,None,None,None,None,None,2962.0,1997.0,2005.0,202.0
1783,366377,COSMO,LICENSED COSMETOLOGIST,11066155.0,NOT RENEWED,N,NaN,PAMELA J,NaN,HASTINGS,...,05/26/2006,None,None,None,None,None,12372.0,1949.0,1983.0,8.0
1844,754523,DESIGN FIRM,DESIGN FIRM - PROFESSIONAL ENGINEERING,184007999-0002,ACTIVE,Y,NaN,BERNADETTE,NaN,WHITE,...,04/26/2021,None,None,None,None,None,1641.0,2018.0,2023.0,209.0
2024,330129,COSMO,LICENSED BARBER,6044330.0,NOT RENEWED,N,NaN,LATIFOU,NaN,AYOOLA,...,05/25/2006,None,None,None,None,None,NaN,1998.0,NaN,857.0
3036,348600,COSMO,LICENSED COSMETOLOGIST,11021558.0,NOT RENEWED,N,NaN,CHRISTINE,NaN,GLOWACKI,...,05/26/2006,None,None,None,None,None,-5207.0,1998.0,1983.0,857.0
3038,375687,COSMO,LICENSED COSMETOLOGIST,11115164.0,NOT RENEWED,N,NaN,EKAETE,NaN,JOHNSON,...,05/26/2006,None,None,None,None,None,NaN,1998.0,NaN,857.0
4752,648837,DENTAL,LICENSED DENTIST,019015070,NOT RENEWED,N,NaN,CHERI L,NaN,SCHUCK,...,02/08/2016,None,None,None,None,None,14841.0,1975.0,2015.0,46.0
4878,1168031,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129314767,NOT RENEWED,N,NaN,SHIRLEY R,E,MINER,...,07/12/2009,None,None,None,None,None,291.0,2008.0,2009.0,205.0
5230,638940,COSMO,LICENSED ESTHETICIAN,131000187.0,NOT RENEWED,N,NaN,AMY L,NaN,LOPRESTI,...,05/30/2006,None,None,None,None,None,2397.0,1993.0,1999.0,205.0
5902,482323,COSMO,LICENSED COSMETOLOGIST,11189716,NOT RENEWED,N,NaN,UBALDO,NaN,SCUDIERO,...,05/30/2006,None,None,None,None,None,7498.0,1983.0,2003.0,98.0
6228,517916,COSMO,LICENSED COSMETOLOGIST,11250723,NOT RENEWED,N,NaN,ROCHELLE,NaN,ROSS,...,05/30/2006,None,None,None,None,None,330.0,1998.0,1999.0,857.0
6512,1260863,FUNERAL AND EMBALMER,LICENSED FUNERAL DIRECTOR AND EMBALMER,034016658,ACTIVE,N,NaN,DAWN,JAMES,GREEN,...,07/07/2021,None,None,None,None,None,3773.0,2013.0,2023.0,223.0
7776,613745,COSMO,LICENSED COSMETOLOGIST TEACHER,12002548.0,NOT RENEWED,N,NaN,STEPHEN C,NaN,LACK,...,05/26/2006,None,None,None,None,None,-4111.0,1998.0,1986.0,857.0
8038,324233,COSMO,LICENSED COSMETOLOGIST,11037415.0,NOT RENEWED,N,NaN,JAVED,NaN,IQBAL,...,05/26/2006,None,None,None,None,None,NaN,1998.0,NaN,857.0
8228,682328,DENTAL,LICENSED DENTIST,019005738,NOT RENEWED,N,NaN,IRENE,NaN,SUTTER,...,10/12/2005,None,None,None,None,None,23790.0,1929.0,1994.0,1.0
8632,361401,COSMO,LICENSED COSMETOLOGIST,11096119.0,INACTIVE,N,NaN,ALICIA,NaN,ROBBINS,...,05/26/2006,None,None,None,None,None,-3746.0,1998.0,1987.0,857.0
8925,701049,DENTAL,REGISTERED DENTAL HYGIENIST,020001341,NOT RENEWED,N,NaN,LAWRENCE,NaN,SINGLETON,...,10/17/2005,None,None,None,None,None,12504.0,1970.0,2004.0,18.0
9024,933875,DETECTIVE BOARD,PERMANENT EMPLOYEE REGISTRATION,129173149,NOT RENEWED,N,NaN,SARA N,NaN,NGUYEN,...,08/03/2006,None,None,None,None,None,897.0,1994.0,1997.0,214.0
9179,518151,COSMO,LICENSED COSMETOLOGIST,11224381,NOT RENEWED,N,NaN,NaN,NaN,NaN,...,05/26/2006,None,None,None,None,None,1345.0,1990.0,1993.0,189.0
9673,540822,COSMO,LICENSED COSMETOLOGIST,11266791,NOT RENEWED,N,NaN,JUAN,A,CORRAL,...,11/01/2017,None,None,None,None,None,4874.0,2004.0,2017.0,200.0

In [17]:
table.columns.values.astype('str')[j]
license_type=table.columns.values.astype('str')[j]
license['License Type']==license_type
license.loc[license['License Type']==license_type]
            
region_mask = ( (license['County']==county_name) &\
              (license['License Type']==license_type))
data=license.loc[region_mask]
data_y=data.groupby(['Original Issue Year'])['days between Original Issue Date and Expiration Date'].median()
data_y

Original Issue Year
1929.0    23790.0
1970.0    12504.0
1971.0     7024.0
1975.0    14841.0
1980.0    15175.0
Name: days between Original Issue Date and Expiration Date, dtype: float64

In [18]:
# BAR chart
x_scl = bqplot.OrdinalScale()
y_scl = bqplot.LinearScale()

# (2) Axis
ax_xcl = bqplot.Axis(label='Date', scale=x_scl)
ax_ycl = bqplot.Axis(label='Duration in Sec', scale=y_scl, 
                    orientation='vertical', side='left')

bar = bqplot.Bars(x=data['Original Issue Year'], y=data_y, scales={"x": x_scl, "y": y_scl})
ax_x = bqplot.Axis(scale=x_scl)
ax_y = bqplot.Axis(scale=y_scl, orientation="vertical")

bqplot.Figure(marks=[bar], axes=[ax_xcl, ax_ycl])

Figure(axes=[Axis(label='Date', scale=OrdinalScale()), Axis(label='Duration in Sec', orientation='vertical', s…

In [20]:
# HEATMAP
# 2. scales
col_sc = bqplot.ColorScale(scheme='Blues')# <3
x_sc = bqplot.OrdinalScale() # ordered bins
y_sc = bqplot.OrdinalScale()

# 3. axis
col_ax = bqplot.ColorAxis(scale=col_sc, label='Mean', orientation='vertical',
                         side='right')
x_ax = bqplot.Axis(scale=x_sc,label='License Type',tick_rotate=90)
y_ax = bqplot.Axis(scale=y_sc, label='County', orientation='vertical')

# 4. Mark - heatmap
heat_map = bqplot.GridHeatMap(color=table, 
                              row=table.index.values.astype('str'),
                              column=table.columns.values.astype('str'),
                              scales={'color':col_sc,
                                                 'row':y_sc,
                                                 'column':x_sc},
                             interactions={'click':'select'},
                             selected_style={'fill':'blue'})

# 5. interactions

fig = bqplot.Figure(marks=[heat_map], axes=[col_ax, x_ax, y_ax])
fig

def get_data_value(change):
    if len(change['owner'].selected) == 1: #only 1 selected
        i,j = change['owner'].selected[0]
        county_name=table.index.values.astype('str')[i]
        license_type=table.columns.values.astype('str')[j]
        region_mask = ( (license['County']==county_name) &\
              (license['License Type']==license_type))
        data=license.loc[region_mask]
        data_y=data.groupby('Original Issue Year')['days between Original Issue Date and Expiration Date'].median()
        bar.x = data['Original Issue Year']
        bar.y = data_y

        
        
heat_map.observe(get_data_value, 'selected')

In [21]:
fig = bqplot.Figure(marks = [heat_map], axes = [col_ax, y_ax, x_ax])
fig_bar = bqplot.Figure(marks = [bar], axes = [ax_xcl, ax_ycl])

In [22]:
# mess with figure layout:
fig.layout.min_width = '550px' 
fig.layout.min_width = '550px'

# side by side figures
figures = ipywidgets.HBox([fig, fig_bar])


# combined
myDashboard = ipywidgets.VBox([figures])
myDashboard

VBox(children=(HBox(children=(Figure(axes=[ColorAxis(label='Mean', orientation='vertical', scale=ColorScale(sc…

ValueError: Unsupported dtype object

ValueError: Unsupported dtype object